server:
  port: 8084

spring:
  application:
    name: ticket-service

eureka:
  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOSTNAME:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/